yes_convert = {
    'Accrington': 'Accrington Stanley',
    'Aldershot': 'Aldershot Town',
    'Birmingham': 'Birmingham City',
    'Blackburn': 'Blackburn Rovers',
    'Bolton': 'Bolton Wanderers',
    'Boston': 'Boston United',
    'Bradford': 'Bradford City',
    'Brighton': 'Brighton & Hove Albion',
    'Bristol Rvs': 'Bristol Rovers',
    'Burton': 'Burton Albion',
    'Cambridge': 'Cambridge United',
    'Cardiff': 'Cardiff City',
    'Carlisle': 'Carlisle United',
    'Charlton': 'Charlton Athletic',
    'Cheltenham': 'Cheltenham Town',
    'Colchester': 'Colchester United',
    'Coventry': 'Coventry City',
    'Crewe': 'Crewe Alexandra',
    'Dag and Red': 'Dagenham and Redbridge',
    'Derby': 'Derby County',
    'Doncaster': 'Doncaster Rovers',
    'Exeter': 'Exeter City',
    'Grimsby': 'Grimsby Town',
    'Hartlepool': 'Hartlepool United',
    'Huddersfield': 'Huddersfield Town',
    'Hull': 'Hull City',
    'Ipswich': 'Ipswich Town',
    'Leeds': 'Leeds United',
    'Leicester': 'Leicester City',
    'Lincoln': 'Lincoln City',
    'Luton': 'Luton Town',
    'Macclesfield': 'Macclesfield Town',
    'Man City': 'Manchester City',
    'Man United': 'Manchester United',
    'Mansfield': 'Mansfield Town',
    'Middlesboro': 'Middlesbrough',
    'Newcastle': 'Newcastle United',
    'Northampton': 'Northampton Town',
    'Norwich': 'Norwich City',
    "Nott'm Forest": 'Nottingham Forest',
    'Oldham': 'Oldham Athletic',
    'Oxford': 'Oxford United',
    'Peterboro': 'Peterborough United',
    'Plymouth': 'Plymouth Argyle',
    'Preston': 'Preston North End',
    'QPR': 'Queens Park Rangers',
    'Rotherham': 'Rotherham United',
    'Scunthorpe': 'Scunthorpe United',
    'Sheffield Weds': 'Sheffield Wednesday',
    'Southend': 'Southend United',
    'Stockport': 'Stockport County',
    'Stoke': 'Stoke City',
    'Swansea': 'Swansea City',
    'Swindon': 'Swindon Town',
    'Torquay': 'Torquay United',
    'Tottenham': 'Tottenham Hotspur',
    'Tranmere': 'Tranmere Rovers',
    'West Brom': 'West Bromwich Albion',
    'West Ham': 'West Ham United',
    'Wigan': 'Wigan Athletic',
    'Wolves': 'Wolverhampton Wanderers',
    'Wycombe': 'Wycombe Wanderers',
    'Yeovil': 'Yeovil Town',
    'York': 'York City',
    'Wimbledon': 'AFC Wimbledon'
}

no_convert = [
    'AFC Wimbledon','Arsenal','Aston Villa','Barnet','Barnsley','Blackpool','Bournemouth',
    'Brentford','Bristol City','Burnley','Bury','Chelsea','Chester','Chesterfield','Crawley Town',
    'Crystal Palace','Darlington','Everton','Fleetwood Town','Forest Green','Fulham','Gillingham',
    'Hereford','Leyton Orient','Liverpool','Middlesbrough','Millwall','Milton Keynes Dons',
    'Morecambe','Newport County','Notts County','Port Vale','Portsmouth','Reading','Rochdale',
    'Sheffield United','Shrewsbury','Southampton','Stevenage','Sunderland','Walsall','Watford','Wrexham']

def map_team_names(team):
    if team in no_convert:
        return team
    return yes_convert.get(team, team)
