create_query = '''
    CREATE TABLE IF NOT EXISTS "player_table" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "fifa_id" INTEGER,
  "DEF" INTEGER,
  "DRI" INTEGER,
  "PAC" INTEGER,
  "PAS" INTEGER,
  "PHY" INTEGER,
  "SHO" INTEGER,
  "acceleration" INTEGER,
  "age" INTEGER,
  "aggression" INTEGER,
  "agility" INTEGER,
  "attacking_work_rate" TEXT,
  "balance" INTEGER,
  "ball_control" INTEGER,
  "club" TEXT,
  "composure" INTEGER,
  "crossing" INTEGER,
  "curve" INTEGER,
  "defensive_work_rate" TEXT,
  "dribbling" INTEGER,
  "finishing" INTEGER,
  "fk_accuracy" INTEGER,
  "foot" TEXT,
  "gk_diving" INTEGER,
  "gk_handling" INTEGER,
  "gk_kicking" INTEGER,
  "gk_positioning" INTEGER,
  "gk_reflexes" INTEGER,
  "growth" INTEGER,
  "heading_accuracy" INTEGER,
  "height" INTEGER,
  "interceptions" INTEGER,
  "international_reputation" INTEGER,
  "joined" TEXT,
  "jumping" INTEGER,
  "loan_date_end" TEXT,
  "long_passing" INTEGER,
  "long_shots" INTEGER,
  "marking" INTEGER,
  "name" TEXT,
  "nationality" TEXT,
  "overall_rating" INTEGER,
  "penalties" INTEGER,
  "position" TEXT,
  "positioning" INTEGER,
  "potential" INTEGER,
  "reactions" INTEGER,
  "release_clause" TEXT,
  "short_passing" INTEGER,
  "shot_power" INTEGER,
  "skill_moves" INTEGER,
  "sliding_tackle" INTEGER,
  "sprint_speed" INTEGER,
  "stamina" INTEGER,
  "standing_tackle" INTEGER,
  "strength" INTEGER,
  "total" INTEGER,
  "total_attacking" INTEGER,
  "total_defending" INTEGER,
  "total_goalkeeping" INTEGER,
  "total_mentality" INTEGER,
  "total_movement" INTEGER,
  "total_power" INTEGER,
  "total_skill" INTEGER,
  "value" TEXT,
  "vision" INTEGER,
  "volleys" INTEGER,
  "wage" TEXT,
  "week_foot" INTEGER,
  "weight" INTEGER,
  "date" TIMESTAMP,
  "query_string" TEXT
);
'''

create_index = "CREATE INDEX player_index ON player_table (id);"
create_fifa_index = "CREATE INDEX fifa_id_index ON player_table (fifa_id);"
create_date_index = "CREATE INDEX date_id_index ON player_table (date);"
create_club_index = "CREATE INDEX club_id_index ON player_table (club);"

drop_query = "DROP TABLE IF EXISTS player_table;"

create_team_feature_table = '''
    CREATE TABLE IF NOT EXISTS "team_feature_table" (
      "id" INTEGER PRIMARY KEY AUTOINCREMENT,
      "club" TEXT,
      "date" TIMESTAMP,
      "acceleration" REAL,
      "age" REAL,
      "aggression" REAL,
      "agility" REAL,
      "balance" REAL,
      "ball_control" REAL,
      "composure" REAL,
      "crossing" REAL,
      "curve" REAL,
      "dribbling" REAL,
      "finishing" REAL,
      "fk_accuracy" REAL,
      "gk_diving" REAL,
      "gk_handling" REAL,
      "gk_kicking" REAL,
      "gk_positioning" REAL,
      "gk_reflexes" REAL,
      "growth" REAL,
      "heading_accuracy" REAL,
      "height" REAL,
      "interceptions" REAL,
      "jumping" REAL,
      "long_passing" REAL,
      "long_shots" REAL,
      "marking" REAL,
      "overall_rating" REAL,
      "penalties" REAL,
      "positioning" REAL,
      "potential" REAL,
      "reactions" REAL,
      "short_passing" REAL,
      "shot_power" REAL,
      "skill_moves" REAL,
      "sliding_tackle" REAL,
      "sprint_speed" REAL,
      "stamina" REAL,
      "standing_tackle" REAL,
      "strength" REAL,
      "vision" REAL,
      "volleys" REAL,
      "weight" REAL
    );'''

drop_team_feature_query = "DROP TABLE IF EXISTS team_feature_table;"
