create_query = '''
    CREATE TABLE IF NOT EXISTS "player_table" (
  "fifa_id" INTEGER PRIMARY KEY,
  "DEF" INTEGER,
  "DRI" INTEGER,
  "PAC" INTEGER,
  "PAS" INTEGER,
  "PHY" INTEGER,
  "SHO" INTEGER,
  "acceleration" INTEGER,
  "age" INTEGER,
  "aggression" INTEGER,
  "agility" INTEGER,
  "attacking_work_rate" TEXT,
  "balance" INTEGER,
  "ball_control" INTEGER,
  "club" TEXT,
  "composure" INTEGER,
  "crossing" INTEGER,
  "curve" INTEGER,
  "defensive_work_rate" TEXT,
  "dribbling" INTEGER,
  "finishing" INTEGER,
  "fk_accuracy" INTEGER,
  "foot" TEXT,
  "gk_diving" INTEGER,
  "gk_handling" INTEGER,
  "gk_kicking" INTEGER,
  "gk_positioning" INTEGER,
  "gk_reflexes" INTEGER,
  "growth" INTEGER,
  "heading_accuracy" INTEGER,
  "height" INTEGER,
  "interceptions" INTEGER,
  "international_reputation" INTEGER,
  "joined" TEXT,
  "jumping" INTEGER,
  "loan_date_end" TEXT,
  "long_passing" INTEGER,
  "long_shots" INTEGER,
  "marking" INTEGER,
  "name" TEXT,
  "nationality" TEXT,
  "overall_rating" INTEGER,
  "penalties" INTEGER,
  "position" TEXT,
  "positioning" INTEGER,
  "potential" INTEGER,
  "reactions" INTEGER,
  "release_clause" TEXT,
  "short_passing" INTEGER,
  "shot_power" INTEGER,
  "skill_moves" INTEGER,
  "sliding_tackle" INTEGER,
  "sprint_speed" INTEGER,
  "stamina" INTEGER,
  "standing_tackle" INTEGER,
  "strength" INTEGER,
  "total" INTEGER,
  "total_attacking" INTEGER,
  "total_defending" INTEGER,
  "total_goalkeeping" INTEGER,
  "total_mentality" INTEGER,
  "total_movement" INTEGER,
  "total_power" INTEGER,
  "total_skill" INTEGER,
  "value" TEXT,
  "vision" INTEGER,
  "volleys" INTEGER,
  "wage" TEXT,
  "week_foot" INTEGER,
  "weight" INTEGER,
  "date" TEXT,
  "query_string" TEXT
);
'''

create_index = "CREATE INDEX player_index ON player_table (fifa_id);"

drop_query = "DROP TABLE IF EXISTS player_table;"
